export default {
    WEB_CONNECT: "WEB_CONNECT",
    IOT_CONNECT: "IOT_CONNECT",
    WEB_MODE: "WEB_MODE",
    IOT_MODE: "IOT_MODE",
    IOT_CONNECT_WEB: "IOT_CONNECT_WEB",
    IOT_RFID_TOKEN: "IOT_RFID_TOKEN",
    WEB_RFID_TOKEN: "IOT_RFID_TOKEN_WEB",
    RFID_REGISTER: "RFID_REGISTER",
    RFID_WEB_RESULT_REGISTER: "RFID_WEB_RESULT_REGISTER",
    RFID_PRESENSI: "RFID_PRESENSI",
    RFID_WEB_RESULT_PRESENSI: "RFID_WEB_RESULT_PRESENSI"
}