export default {
    WEB_CONNECT: "WEB_CONNECT",
    IOT_CONNECT: "IOT_CONNECT",
    WEB_MODE: "WEB_MODE",
    IOT_MODE: "IOT_MODE",
    IOT_RFID_TOKEN: "IOT_RFID_TOKEN",
    WEB_RFID_TOKEN: "IOT_RFID_TOKEN_WEB"
}